---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/sapienti/public_html/appx/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - composer install
